version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - mvn package
      - docker build -t irunninglog/api-graphql:latest .
      - docker tag irunninglog/api-graphql:latest 329192577320.dkr.ecr.us-east-1.amazonaws.com/irunninglog/api-graphql:latest
#  post_build:
#    commands:
#      - echo Build completed on `date`
#      - echo Pushing the Docker image...
#      - docker push 329192577320.dkr.ecr.us-east-1.amazonaws.com/irunninglog/api:latest
#      - printf '[{"name":"irunninglog-api","imageUri":"%s"}]' 329192577320.dkr.ecr.us-east-1.amazonaws.com/irunninglog/api:latest > imagedefinitions.json
#
#artifacts:
#  files:
#    - imagedefinitions.json