version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - mvn package
      - docker build -t irunninglog/api-graphql:latest .
      - docker tag irunninglog/api-graphql:latest 329192577320.dkr.ecr.us-east-1.amazonaws.com/irunninglog/api-graphql:latest
  post_build:
    commands:
      - docker push 329192577320.dkr.ecr.us-east-1.amazonaws.com/irunninglog/api-graphql:latest
      - printf '[{"name":"irunninglog-api-graphql","imageUri":"%s"}]' 329192577320.dkr.ecr.us-east-1.amazonaws.com/irunninglog/api-graphql:latest > imagedefinitions.json

#artifacts:
#  files:
#    - imagedefinitions.json